apiVersion: v1
kind: Service
metadata:
  name: social-app-service1
spec:
  type: NodePort
  selector:
    app: smedia-app
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30211 # You can change this to any available port number above 30000